### ISSUE TITLE
Release plans?

### ISSUE THREAD

**Issue by maerteijn** [django-commons/django-fsm-2#14]
Hi!

Thanks for taking care of this excellent package! Do you also have plans to do some official releases to pypi?

**Comment by pfouque** [comment]
Hi @maerteijn 
There has been some activity on the main project recently, so I'm still hoping for an official release.

If it doesn't happen, I may consider releasing this version, but I would seriously prefer something official:
- Release a new version (more recent than 2022/08)
- Transfer to jazzband
- Adding some maintainers
- Officially declaring the main project as archived

At least, now we can use the official repository as a git source...

**Comment by pfouque** [comment]
Hi @maerteijn , 
Since it seems clear there will be no new official release, the first alternative release is freshly available on PYPI: https://pypi.org/project/django-fsm-2/

**Comment by RemiDesgrange** [comment]
Do you still have plan to move this project under jazzband org ? (like discussed in viewflow/django-fsm#298 )

**Comment by wgordon17** [comment]
Hey all 👋 Given the recent archival of `django-fsm` and them forcing everyone to `viewflow`, I'd like to understand the plans here with `django-fsm-2`. I have no intentions of migrating to `viewflow`, and would ideally like to stick with a `django-fsm`-esque package. Thanks!

**Comment by Natim** [comment]
The plan is to maintain django-fsm with this package. It's been released to pypi, feel free to use it.

**Comment by wgordon17** [comment]
@Natim That's _great_ to hear 🎉 I'd love to be involved if you want/need the help ¯\_(ツ)_/¯ I'm not necessarily sure what the project _needs_, but if there's anything you can think of I wouldn't mind looking. Willing to do my part to keep this library alive ❤️

**Comment by Natim** [comment]
With pleasure, feel free to subscribe to the repository and to review PR or Issues that would be provided, this will help us a lot.

**Comment by Natim** [comment]
> Do you still have plan to move this project under jazzband org ? (like discussed in [viewflow/django-fsm#298](https://github.com/viewflow/django-fsm/issues/298) )

The project officially moved to the [django-commons](https://github.com/django-commons/django-fsm-2) initiative! I consider this issue as completed!
